### ISSUE TITLE
Ensuring application instances do not overwrite each other

### ISSUE THREAD

**Issue by atgeirr** [MSO4SC/resources#20]
In the current implementation, if I create 2 instances of the "OPM Flow app" they will write to the same directories. Input is not too problematic, unless the two cases run have the same name, yet are different. However output will be written to the same files, and probably end up corrupted.

To resolve this the app instance should be run in a new, empty directory with a unique, generated name. Currently I can specify the workdir, but I think that should only be the base directory, and the orchestrator should automatically generate a unique dir within the workdir.

**Comment by emepetres** [comment]
Resolved in MSO4SC/cloudify-hpc-plugin repo.
