### ISSUE TITLE
Update some blueprints to enable cloud computing

### ISSUE THREAD

**Issue by victorsndvg** [MSO4SC/resources#32]
as I explained in the WP3-4-5 meeting today, we need some blueprints updated and working in order to perform some testing in the cloud, compare with HPC and collect some metrics.

I need your blueprints working as they are the entrypoint to understand how to (1) run them directly in the HPC using the orchestrator and (2) use them as an entrypoint to understand how to run the apps and translate them to shell scripts.

I talk 1 by 1 to choose some apps for this experiment. We agree in this list:

[x] OPM-Flow (with norne dataset)
[x] ZibAffinity (with arrayjobs of size 2)
[ ] FEniCS  (an iterative job)
[ ] Feel++ (torsion bar)

OPM and ZibAffinity blueprints are ready and working.

I would also like to test FEniCX and Feel++. 

@gdolle and @ncde can you provide some working blueprints?

Is planned to publish these results in a paper. The deadline for the paper is the 15th of May. We should have this blueprints at leas 1 week before. Do you think it's possible?

Thanks in advance!

**Comment by atgeirr** [comment]
It would be great to test the ensemble case as well in the cloud setting, is it possible to do that as well? I can provide the test case and help with the work (and writing).

**Comment by gdolle** [comment]
Yes I'll update the existing one by the end of the week.

**Comment by victorsndvg** [comment]
Ok, thanks @gdolle !

@atgeirr , we used OPM for the monolithic case, but we could also test it with the ensemble case. The blueprint is ready to run?

**Comment by atgeirr** [comment]
> @atgeirr , we used OPM for the monolithic case, but we could also test it with the ensemble case. The blueprint is ready to run?

It should be. It has been successfully tested once... However, the scripts may need rewriting, as they use $SLURM_ARRAY_TASK_ID. Not sure if that is available in your setting? We should adapt it anyway; the "ensemble in a cloud" case is likely to be the most used approach.

**Comment by victorsndvg** [comment]
Hi @atgeirr ,

is your blueprint prepared to work if we change the `scale` and/or `parallel_tasks` properties?
Is there any other public input dataset in order to make longer the execution time?

Thanks!
