### ISSUE TITLE
ft2 infrastructure definitions

### ISSUE THREAD

**Issue by Trophime** [MSO4SC/resources#45]
Hi,
I'm a bit suprised by the figures for partition at FTII defined in the yaml file.
I've run tests going up to 216 procs (9 cpus) on **thinnodes** partition.
So there shall be more than 8 cpus...
Can you update the figures?

@emepetres  I'm also wondering what happens when:
if I request more than 8 cpus or 144 procs would my job would be rejected?

**Comment by Trophime** [comment]
@carlosffernandez could maybe comment on that figures?

**Comment by emepetres** [comment]
@Trophime actually that file was completed by me and there are some things that are not entirely true, as you found.

The idea of this data is to be used in the future to better input validation/automation, but for now it is not used by the portal nor the orchestrator.
