### ISSUE TITLE
Trouble with data migration: newhome error and "quick" work around

### ISSUE THREAD

**Issue by Trophime** [MSO4SC/resources#6]
With the undergoing data migration planned on cesga, starting singularity may fails with a message like that:
```
ERROR  : Base home directory does not exist within the container: /newhome
ABORT  : Retval = 255
```
to fix this the proper way is to use `-H $HOME:/home/$USER`.

However in blueprint.yml you can only mount volumes so far.
As suggested by @victorsndvg a simple work around is to make the folliwing change in your blueprint file:
```
                volumes:
                    - '/scratch'
                    - '${LUSTRE}/feel:/feel -H $HOME:/home/$USER'
```

**Comment by emepetres** [comment]
New property `home` can now be added to job_options property to mount the home directory:

----
home: '$HOME:/home/$USER'
                volumes:
                    - '/scratch'
----
